version: '3'

services:
  # Load-balancer service
  app:
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - '8080:8080'
    restart: unless-stopped

  # Requests spammer service
  spam:
    build:
      context: .
      dockerfile: Dockerfile.spam
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - TARGET_HOST=172.17.0.1
